version: '3.8'

services:
  web:
    build: .
    container_name: bolos-app
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      # Mapeamos la base de datos local al contenedor para no perder las partidas
      - ./bowling.db:/app/bowling.db